
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action QuitButton;

	private global::Gtk.Action AboutButton;

	private global::Gtk.Action RunButton;

	private global::Gtk.Action ResetButton;

	private global::Gtk.Action StopButton;

	private global::Gtk.Action LoadCentroidsButton;

	private global::Gtk.Action SaveDataButton;

	private global::Gtk.Action PlotButton;

	private global::Gtk.Action SavePlotButton;

	private global::Gtk.Fixed MainLayout;

	private global::Gtk.Toolbar MainToolbar;

	private global::Gtk.Notebook MainNotebook;

	private global::Gtk.Fixed PageLayoutData;

	private global::Gtk.Entry DataFileName;

	private global::Gtk.Button OpenDataButton;

	private global::Gtk.Button ReloadDataButton;

	private global::Gtk.Label LabelDataFilename;

	private global::Gtk.ScrolledWindow DataWindow;

	private global::Gtk.TextView DataView;

	private global::Gtk.Button ClearDataButton;

	private global::Gtk.ComboBox DelimiterBox;

	private global::Gtk.Label LabelDelimeters;

	private global::Gtk.Label LabelFeatures;

	private global::Gtk.SpinButton Features;

	private global::Gtk.Label LabelDataPoints;

	private global::Gtk.SpinButton DataPoints;

	private global::Gtk.CheckButton IgnoreLastColumn;

	private global::Gtk.Label LabelPageData;

	private global::Gtk.Fixed PageLayoutCluster;

	private global::Gtk.Label LabelClusters;

	private global::Gtk.ScrolledWindow ClusterWindow;

	private global::Gtk.TextView ClusterView;

	private global::Gtk.Label LabelCentroids;

	private global::Gtk.ScrolledWindow CentroidsWindow;

	private global::Gtk.TextView CentroidsView;

	private global::Gtk.Label LabelNumClusters;

	private global::Gtk.SpinButton NumClusters;

	private global::Gtk.Label LabelClustering;

	private global::Gtk.ProgressBar ClusteringProgress;

	private global::Gtk.Toolbar ClusteringToolbar;

	private global::Gtk.Label LabelIterations;

	private global::Gtk.SpinButton MaxIterations;

	private global::Gtk.Label LabelError;

	private global::Gtk.Entry Error;

	private global::Gtk.Label LabelPageCluster;

	private global::Gtk.Fixed PageLayoutSave;

	private global::Gtk.Entry CentroidFileName;

	private global::Gtk.Entry ClusterFileName;

	private global::Gtk.Button OpenCentroidsButton;

	private global::Gtk.Button SaveCentroidsButton;

	private global::Gtk.Button OpenClustersButton;

	private global::Gtk.Button SaveClustersButton;

	private global::Gtk.Toolbar CentroidsToolbar;

	private global::Gtk.Label LabelLoadCentroids;

	private global::Gtk.Toolbar SaveToolbar;

	private global::Gtk.Label LabelSaveData;

	private global::Gtk.Entry NewDataFileName;

	private global::Gtk.Label LabelNewData;

	private global::Gtk.Label LabelPageSave;

	private global::Gtk.Fixed LayoutPagePlot;

	private global::Gtk.Image PlotImage;

	private global::Gtk.Toolbar PlotToolbar;

	private global::Gtk.Label LabelPlotFeatures;

	private global::Gtk.Label LabelX;

	private global::Gtk.SpinButton Feature1;

	private global::Gtk.Label LabelY;

	private global::Gtk.SpinButton Feature2;

	private global::Gtk.Label LabelPagePlot;

	private global::Gtk.Fixed PageLayoutAbout;

	private global::Gtk.Label LabelAboutSoftware;

	private global::Gtk.ScrolledWindow AboutWindow;

	private global::Gtk.TextView AboutView;

	private global::Gtk.Label LabelCredits;

	private global::Gtk.ScrolledWindow CreditsWindow;

	private global::Gtk.TextView CreditsView;

	private global::Gtk.Image ClusteringImage;

	private global::Gtk.Label LabelPageAbout;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.QuitButton = new global::Gtk.Action("QuitButton", null, global::Mono.Unix.Catalog.GetString("Exit GTK Clustering"), "gtk-quit");
		w1.Add(this.QuitButton, null);
		this.AboutButton = new global::Gtk.Action("AboutButton", null, global::Mono.Unix.Catalog.GetString("About GTK Clustering"), "gtk-info");
		w1.Add(this.AboutButton, null);
		this.RunButton = new global::Gtk.Action("RunButton", null, global::Mono.Unix.Catalog.GetString("Start clustering"), "gtk-media-play");
		w1.Add(this.RunButton, null);
		this.ResetButton = new global::Gtk.Action("ResetButton", null, global::Mono.Unix.Catalog.GetString("Restart clustering"), "gtk-media-rewind");
		w1.Add(this.ResetButton, null);
		this.StopButton = new global::Gtk.Action("StopButton", null, global::Mono.Unix.Catalog.GetString("Stop clustering"), "gtk-media-stop");
		w1.Add(this.StopButton, null);
		this.LoadCentroidsButton = new global::Gtk.Action("LoadCentroidsButton", null, global::Mono.Unix.Catalog.GetString("Load centroids"), "gtk-properties");
		w1.Add(this.LoadCentroidsButton, null);
		this.SaveDataButton = new global::Gtk.Action("SaveDataButton", null, global::Mono.Unix.Catalog.GetString("Save as new data"), "gtk-save-as");
		w1.Add(this.SaveDataButton, null);
		this.PlotButton = new global::Gtk.Action("PlotButton", null, global::Mono.Unix.Catalog.GetString("Plot clusters"), "gtk-media-play");
		w1.Add(this.PlotButton, null);
		this.SavePlotButton = new global::Gtk.Action("SavePlotButton", null, global::Mono.Unix.Catalog.GetString("Save plot as image"), "gtk-save");
		w1.Add(this.SavePlotButton, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.WidthRequest = 800;
		this.HeightRequest = 600;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource("Clustering.atoms.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.Resizable = false;
		this.DefaultWidth = 800;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainLayout = new global::Gtk.Fixed();
		this.MainLayout.Name = "MainLayout";
		this.MainLayout.HasWindow = false;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'MainToolbar\'><toolitem name=\'AboutButton\' action=\'AboutButton\'" +
				"/><toolitem name=\'QuitButton\' action=\'QuitButton\'/></toolbar></ui>");
		this.MainToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/MainToolbar")));
		this.MainToolbar.Name = "MainToolbar";
		this.MainToolbar.ShowArrow = false;
		this.MainToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.MainLayout.Add(this.MainToolbar);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.MainToolbar]));
		w2.X = 20;
		w2.Y = 10;
		// Container child MainLayout.Gtk.Fixed+FixedChild
		this.MainNotebook = new global::Gtk.Notebook();
		this.MainNotebook.WidthRequest = 760;
		this.MainNotebook.HeightRequest = 520;
		this.MainNotebook.CanFocus = true;
		this.MainNotebook.Name = "MainNotebook";
		this.MainNotebook.CurrentPage = 0;
		// Container child MainNotebook.Gtk.Notebook+NotebookChild
		this.PageLayoutData = new global::Gtk.Fixed();
		this.PageLayoutData.Name = "PageLayoutData";
		this.PageLayoutData.HasWindow = false;
		// Container child PageLayoutData.Gtk.Fixed+FixedChild
		this.DataFileName = new global::Gtk.Entry();
		this.DataFileName.WidthRequest = 300;
		this.DataFileName.Name = "DataFileName";
		this.DataFileName.IsEditable = true;
		this.DataFileName.InvisibleChar = '•';
		this.PageLayoutData.Add(this.DataFileName);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutData[this.DataFileName]));
		w3.X = 20;
		w3.Y = 40;
		// Container child PageLayoutData.Gtk.Fixed+FixedChild
		this.OpenDataButton = new global::Gtk.Button();
		this.OpenDataButton.Name = "OpenDataButton";
		this.OpenDataButton.FocusOnClick = false;
		global::Gtk.Image w4 = new global::Gtk.Image();
		w4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
		this.OpenDataButton.Image = w4;
		this.PageLayoutData.Add(this.OpenDataButton);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutData[this.OpenDataButton]));
		w5.X = 330;
		w5.Y = 40;
		// Container child PageLayoutData.Gtk.Fixed+FixedChild
		this.ReloadDataButton = new global::Gtk.Button();
		this.ReloadDataButton.Name = "ReloadDataButton";
		this.ReloadDataButton.FocusOnClick = false;
		global::Gtk.Image w6 = new global::Gtk.Image();
		w6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-revert-to-saved", global::Gtk.IconSize.Menu);
		this.ReloadDataButton.Image = w6;
		this.PageLayoutData.Add(this.ReloadDataButton);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutData[this.ReloadDataButton]));
		w7.X = 360;
		w7.Y = 40;
		// Container child PageLayoutData.Gtk.Fixed+FixedChild
		this.LabelDataFilename = new global::Gtk.Label();
		this.LabelDataFilename.Name = "LabelDataFilename";
		this.LabelDataFilename.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Data</b>");
		this.LabelDataFilename.UseMarkup = true;
		this.PageLayoutData.Add(this.LabelDataFilename);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutData[this.LabelDataFilename]));
		w8.X = 20;
		w8.Y = 20;
		// Container child PageLayoutData.Gtk.Fixed+FixedChild
		this.DataWindow = new global::Gtk.ScrolledWindow();
		this.DataWindow.WidthRequest = 370;
		this.DataWindow.HeightRequest = 140;
		this.DataWindow.Name = "DataWindow";
		this.DataWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child DataWindow.Gtk.Container+ContainerChild
		this.DataView = new global::Gtk.TextView();
		this.DataView.CanFocus = true;
		this.DataView.Name = "DataView";
		this.DataWindow.Add(this.DataView);
		this.PageLayoutData.Add(this.DataWindow);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutData[this.DataWindow]));
		w10.X = 20;
		w10.Y = 80;
		// Container child PageLayoutData.Gtk.Fixed+FixedChild
		this.ClearDataButton = new global::Gtk.Button();
		this.ClearDataButton.CanFocus = true;
		this.ClearDataButton.Name = "ClearDataButton";
		this.ClearDataButton.UseUnderline = true;
		this.ClearDataButton.FocusOnClick = false;
		this.ClearDataButton.Label = global::Mono.Unix.Catalog.GetString("Clear");
		this.PageLayoutData.Add(this.ClearDataButton);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutData[this.ClearDataButton]));
		w11.X = 20;
		w11.Y = 230;
		// Container child PageLayoutData.Gtk.Fixed+FixedChild
		this.DelimiterBox = global::Gtk.ComboBox.NewText();
		this.DelimiterBox.WidthRequest = 200;
		this.DelimiterBox.Name = "DelimiterBox";
		this.PageLayoutData.Add(this.DelimiterBox);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutData[this.DelimiterBox]));
		w12.X = 420;
		w12.Y = 40;
		// Container child PageLayoutData.Gtk.Fixed+FixedChild
		this.LabelDelimeters = new global::Gtk.Label();
		this.LabelDelimeters.Name = "LabelDelimeters";
		this.LabelDelimeters.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Delimiters</b>");
		this.LabelDelimeters.UseMarkup = true;
		this.PageLayoutData.Add(this.LabelDelimeters);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutData[this.LabelDelimeters]));
		w13.X = 420;
		w13.Y = 20;
		// Container child PageLayoutData.Gtk.Fixed+FixedChild
		this.LabelFeatures = new global::Gtk.Label();
		this.LabelFeatures.Name = "LabelFeatures";
		this.LabelFeatures.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Features</b>");
		this.LabelFeatures.UseMarkup = true;
		this.PageLayoutData.Add(this.LabelFeatures);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutData[this.LabelFeatures]));
		w14.X = 420;
		w14.Y = 80;
		// Container child PageLayoutData.Gtk.Fixed+FixedChild
		this.Features = new global::Gtk.SpinButton(0D, 1000D, 1D);
		this.Features.WidthRequest = 200;
		this.Features.Name = "Features";
		this.Features.Adjustment.PageIncrement = 1D;
		this.Features.ClimbRate = 1D;
		this.Features.Numeric = true;
		this.PageLayoutData.Add(this.Features);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutData[this.Features]));
		w15.X = 420;
		w15.Y = 100;
		// Container child PageLayoutData.Gtk.Fixed+FixedChild
		this.LabelDataPoints = new global::Gtk.Label();
		this.LabelDataPoints.Name = "LabelDataPoints";
		this.LabelDataPoints.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Data points</b>");
		this.LabelDataPoints.UseMarkup = true;
		this.PageLayoutData.Add(this.LabelDataPoints);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutData[this.LabelDataPoints]));
		w16.X = 420;
		w16.Y = 170;
		// Container child PageLayoutData.Gtk.Fixed+FixedChild
		this.DataPoints = new global::Gtk.SpinButton(0D, 100000D, 1D);
		this.DataPoints.WidthRequest = 200;
		this.DataPoints.Name = "DataPoints";
		this.DataPoints.Adjustment.PageIncrement = 1D;
		this.DataPoints.ClimbRate = 1D;
		this.DataPoints.Numeric = true;
		this.PageLayoutData.Add(this.DataPoints);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutData[this.DataPoints]));
		w17.X = 420;
		w17.Y = 190;
		// Container child PageLayoutData.Gtk.Fixed+FixedChild
		this.IgnoreLastColumn = new global::Gtk.CheckButton();
		this.IgnoreLastColumn.Name = "IgnoreLastColumn";
		this.IgnoreLastColumn.Label = global::Mono.Unix.Catalog.GetString("Ignore last column");
		this.IgnoreLastColumn.Active = true;
		this.IgnoreLastColumn.DrawIndicator = true;
		this.IgnoreLastColumn.UseUnderline = true;
		this.PageLayoutData.Add(this.IgnoreLastColumn);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutData[this.IgnoreLastColumn]));
		w18.X = 420;
		w18.Y = 140;
		this.MainNotebook.Add(this.PageLayoutData);
		// Notebook tab
		this.LabelPageData = new global::Gtk.Label();
		this.LabelPageData.Name = "LabelPageData";
		this.LabelPageData.LabelProp = global::Mono.Unix.Catalog.GetString("Data");
		this.MainNotebook.SetTabLabel(this.PageLayoutData, this.LabelPageData);
		this.LabelPageData.ShowAll();
		// Container child MainNotebook.Gtk.Notebook+NotebookChild
		this.PageLayoutCluster = new global::Gtk.Fixed();
		this.PageLayoutCluster.Name = "PageLayoutCluster";
		this.PageLayoutCluster.HasWindow = false;
		// Container child PageLayoutCluster.Gtk.Fixed+FixedChild
		this.LabelClusters = new global::Gtk.Label();
		this.LabelClusters.Name = "LabelClusters";
		this.LabelClusters.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Cluster/Classification</b>");
		this.LabelClusters.UseMarkup = true;
		this.PageLayoutCluster.Add(this.LabelClusters);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutCluster[this.LabelClusters]));
		w20.X = 420;
		w20.Y = 20;
		// Container child PageLayoutCluster.Gtk.Fixed+FixedChild
		this.ClusterWindow = new global::Gtk.ScrolledWindow();
		this.ClusterWindow.WidthRequest = 310;
		this.ClusterWindow.HeightRequest = 140;
		this.ClusterWindow.Name = "ClusterWindow";
		this.ClusterWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child ClusterWindow.Gtk.Container+ContainerChild
		this.ClusterView = new global::Gtk.TextView();
		this.ClusterView.Name = "ClusterView";
		this.ClusterView.Editable = false;
		this.ClusterWindow.Add(this.ClusterView);
		this.PageLayoutCluster.Add(this.ClusterWindow);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutCluster[this.ClusterWindow]));
		w22.X = 420;
		w22.Y = 40;
		// Container child PageLayoutCluster.Gtk.Fixed+FixedChild
		this.LabelCentroids = new global::Gtk.Label();
		this.LabelCentroids.Name = "LabelCentroids";
		this.LabelCentroids.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Centroids</b>");
		this.LabelCentroids.UseMarkup = true;
		this.PageLayoutCluster.Add(this.LabelCentroids);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutCluster[this.LabelCentroids]));
		w23.X = 20;
		w23.Y = 190;
		// Container child PageLayoutCluster.Gtk.Fixed+FixedChild
		this.CentroidsWindow = new global::Gtk.ScrolledWindow();
		this.CentroidsWindow.WidthRequest = 370;
		this.CentroidsWindow.HeightRequest = 140;
		this.CentroidsWindow.Name = "CentroidsWindow";
		this.CentroidsWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child CentroidsWindow.Gtk.Container+ContainerChild
		this.CentroidsView = new global::Gtk.TextView();
		this.CentroidsView.Name = "CentroidsView";
		this.CentroidsView.Editable = false;
		this.CentroidsWindow.Add(this.CentroidsView);
		this.PageLayoutCluster.Add(this.CentroidsWindow);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutCluster[this.CentroidsWindow]));
		w25.X = 20;
		w25.Y = 210;
		// Container child PageLayoutCluster.Gtk.Fixed+FixedChild
		this.LabelNumClusters = new global::Gtk.Label();
		this.LabelNumClusters.Name = "LabelNumClusters";
		this.LabelNumClusters.LabelProp = global::Mono.Unix.Catalog.GetString("<b># of Clusters</b>");
		this.LabelNumClusters.UseMarkup = true;
		this.PageLayoutCluster.Add(this.LabelNumClusters);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutCluster[this.LabelNumClusters]));
		w26.X = 420;
		w26.Y = 190;
		// Container child PageLayoutCluster.Gtk.Fixed+FixedChild
		this.NumClusters = new global::Gtk.SpinButton(1D, 1000D, 1D);
		this.NumClusters.WidthRequest = 310;
		this.NumClusters.CanFocus = true;
		this.NumClusters.Name = "NumClusters";
		this.NumClusters.Adjustment.PageIncrement = 1D;
		this.NumClusters.ClimbRate = 1D;
		this.NumClusters.Numeric = true;
		this.NumClusters.Value = 1D;
		this.PageLayoutCluster.Add(this.NumClusters);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutCluster[this.NumClusters]));
		w27.X = 420;
		w27.Y = 210;
		// Container child PageLayoutCluster.Gtk.Fixed+FixedChild
		this.LabelClustering = new global::Gtk.Label();
		this.LabelClustering.Name = "LabelClustering";
		this.LabelClustering.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Clustering</b>");
		this.LabelClustering.UseMarkup = true;
		this.PageLayoutCluster.Add(this.LabelClustering);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutCluster[this.LabelClustering]));
		w28.X = 20;
		w28.Y = 370;
		// Container child PageLayoutCluster.Gtk.Fixed+FixedChild
		this.ClusteringProgress = new global::Gtk.ProgressBar();
		this.ClusteringProgress.WidthRequest = 370;
		this.ClusteringProgress.HeightRequest = 30;
		this.ClusteringProgress.Name = "ClusteringProgress";
		this.PageLayoutCluster.Add(this.ClusteringProgress);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutCluster[this.ClusteringProgress]));
		w29.X = 20;
		w29.Y = 390;
		// Container child PageLayoutCluster.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'ClusteringToolbar\'><toolitem name=\'RunButton\' action=\'RunButto" +
				"n\'/><toolitem name=\'StopButton\' action=\'StopButton\'/><toolitem name=\'ResetButton" +
				"\' action=\'ResetButton\'/></toolbar></ui>");
		this.ClusteringToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/ClusteringToolbar")));
		this.ClusteringToolbar.Name = "ClusteringToolbar";
		this.ClusteringToolbar.ShowArrow = false;
		this.ClusteringToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.PageLayoutCluster.Add(this.ClusteringToolbar);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutCluster[this.ClusteringToolbar]));
		w30.X = 20;
		w30.Y = 430;
		// Container child PageLayoutCluster.Gtk.Fixed+FixedChild
		this.LabelIterations = new global::Gtk.Label();
		this.LabelIterations.Name = "LabelIterations";
		this.LabelIterations.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Maximum # of Iterations</b>");
		this.LabelIterations.UseMarkup = true;
		this.PageLayoutCluster.Add(this.LabelIterations);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutCluster[this.LabelIterations]));
		w31.X = 420;
		w31.Y = 250;
		// Container child PageLayoutCluster.Gtk.Fixed+FixedChild
		this.MaxIterations = new global::Gtk.SpinButton(100D, 1000000D, 1D);
		this.MaxIterations.WidthRequest = 310;
		this.MaxIterations.CanFocus = true;
		this.MaxIterations.Name = "MaxIterations";
		this.MaxIterations.Adjustment.PageIncrement = 1D;
		this.MaxIterations.ClimbRate = 1D;
		this.MaxIterations.Numeric = true;
		this.MaxIterations.Value = 100D;
		this.PageLayoutCluster.Add(this.MaxIterations);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutCluster[this.MaxIterations]));
		w32.X = 420;
		w32.Y = 270;
		// Container child PageLayoutCluster.Gtk.Fixed+FixedChild
		this.LabelError = new global::Gtk.Label();
		this.LabelError.Name = "LabelError";
		this.LabelError.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Average SSE/Error</b>");
		this.LabelError.UseMarkup = true;
		this.PageLayoutCluster.Add(this.LabelError);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutCluster[this.LabelError]));
		w33.X = 420;
		w33.Y = 310;
		// Container child PageLayoutCluster.Gtk.Fixed+FixedChild
		this.Error = new global::Gtk.Entry();
		this.Error.WidthRequest = 310;
		this.Error.Name = "Error";
		this.Error.IsEditable = false;
		this.Error.InvisibleChar = '•';
		this.PageLayoutCluster.Add(this.Error);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutCluster[this.Error]));
		w34.X = 420;
		w34.Y = 330;
		this.MainNotebook.Add(this.PageLayoutCluster);
		global::Gtk.Notebook.NotebookChild w35 = ((global::Gtk.Notebook.NotebookChild)(this.MainNotebook[this.PageLayoutCluster]));
		w35.Position = 1;
		// Notebook tab
		this.LabelPageCluster = new global::Gtk.Label();
		this.LabelPageCluster.Name = "LabelPageCluster";
		this.LabelPageCluster.LabelProp = global::Mono.Unix.Catalog.GetString("Compute");
		this.MainNotebook.SetTabLabel(this.PageLayoutCluster, this.LabelPageCluster);
		this.LabelPageCluster.ShowAll();
		// Container child MainNotebook.Gtk.Notebook+NotebookChild
		this.PageLayoutSave = new global::Gtk.Fixed();
		this.PageLayoutSave.Name = "PageLayoutSave";
		this.PageLayoutSave.HasWindow = false;
		// Container child PageLayoutSave.Gtk.Fixed+FixedChild
		this.CentroidFileName = new global::Gtk.Entry();
		this.CentroidFileName.WidthRequest = 300;
		this.CentroidFileName.Name = "CentroidFileName";
		this.CentroidFileName.IsEditable = true;
		this.CentroidFileName.InvisibleChar = '•';
		this.PageLayoutSave.Add(this.CentroidFileName);
		global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutSave[this.CentroidFileName]));
		w36.X = 20;
		w36.Y = 190;
		// Container child PageLayoutSave.Gtk.Fixed+FixedChild
		this.ClusterFileName = new global::Gtk.Entry();
		this.ClusterFileName.WidthRequest = 240;
		this.ClusterFileName.Name = "ClusterFileName";
		this.ClusterFileName.IsEditable = true;
		this.ClusterFileName.InvisibleChar = '•';
		this.PageLayoutSave.Add(this.ClusterFileName);
		global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutSave[this.ClusterFileName]));
		w37.X = 420;
		w37.Y = 190;
		// Container child PageLayoutSave.Gtk.Fixed+FixedChild
		this.OpenCentroidsButton = new global::Gtk.Button();
		this.OpenCentroidsButton.Name = "OpenCentroidsButton";
		this.OpenCentroidsButton.FocusOnClick = false;
		global::Gtk.Image w38 = new global::Gtk.Image();
		w38.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
		this.OpenCentroidsButton.Image = w38;
		this.PageLayoutSave.Add(this.OpenCentroidsButton);
		global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutSave[this.OpenCentroidsButton]));
		w39.X = 330;
		w39.Y = 190;
		// Container child PageLayoutSave.Gtk.Fixed+FixedChild
		this.SaveCentroidsButton = new global::Gtk.Button();
		this.SaveCentroidsButton.Name = "SaveCentroidsButton";
		this.SaveCentroidsButton.FocusOnClick = false;
		global::Gtk.Image w40 = new global::Gtk.Image();
		w40.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Menu);
		this.SaveCentroidsButton.Image = w40;
		this.PageLayoutSave.Add(this.SaveCentroidsButton);
		global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutSave[this.SaveCentroidsButton]));
		w41.X = 360;
		w41.Y = 190;
		// Container child PageLayoutSave.Gtk.Fixed+FixedChild
		this.OpenClustersButton = new global::Gtk.Button();
		this.OpenClustersButton.Name = "OpenClustersButton";
		this.OpenClustersButton.FocusOnClick = false;
		global::Gtk.Image w42 = new global::Gtk.Image();
		w42.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-open", global::Gtk.IconSize.Menu);
		this.OpenClustersButton.Image = w42;
		this.PageLayoutSave.Add(this.OpenClustersButton);
		global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutSave[this.OpenClustersButton]));
		w43.X = 670;
		w43.Y = 190;
		// Container child PageLayoutSave.Gtk.Fixed+FixedChild
		this.SaveClustersButton = new global::Gtk.Button();
		this.SaveClustersButton.Name = "SaveClustersButton";
		this.SaveClustersButton.FocusOnClick = false;
		global::Gtk.Image w44 = new global::Gtk.Image();
		w44.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-save", global::Gtk.IconSize.Menu);
		this.SaveClustersButton.Image = w44;
		this.PageLayoutSave.Add(this.SaveClustersButton);
		global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutSave[this.SaveClustersButton]));
		w45.X = 700;
		w45.Y = 190;
		// Container child PageLayoutSave.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'CentroidsToolbar\'><toolitem name=\'LoadCentroidsButton\' action=" +
				"\'LoadCentroidsButton\'/></toolbar></ui>");
		this.CentroidsToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/CentroidsToolbar")));
		this.CentroidsToolbar.Name = "CentroidsToolbar";
		this.CentroidsToolbar.ShowArrow = false;
		this.CentroidsToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.PageLayoutSave.Add(this.CentroidsToolbar);
		global::Gtk.Fixed.FixedChild w46 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutSave[this.CentroidsToolbar]));
		w46.X = 20;
		w46.Y = 430;
		// Container child PageLayoutSave.Gtk.Fixed+FixedChild
		this.LabelLoadCentroids = new global::Gtk.Label();
		this.LabelLoadCentroids.Name = "LabelLoadCentroids";
		this.LabelLoadCentroids.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Initialize centroids</b>");
		this.LabelLoadCentroids.UseMarkup = true;
		this.PageLayoutSave.Add(this.LabelLoadCentroids);
		global::Gtk.Fixed.FixedChild w47 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutSave[this.LabelLoadCentroids]));
		w47.X = 70;
		w47.Y = 440;
		// Container child PageLayoutSave.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'SaveToolbar\'><toolitem name=\'SaveDataButton\' action=\'SaveDataB" +
				"utton\'/></toolbar></ui>");
		this.SaveToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/SaveToolbar")));
		this.SaveToolbar.Name = "SaveToolbar";
		this.SaveToolbar.ShowArrow = false;
		this.SaveToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.PageLayoutSave.Add(this.SaveToolbar);
		global::Gtk.Fixed.FixedChild w48 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutSave[this.SaveToolbar]));
		w48.X = 20;
		w48.Y = 380;
		// Container child PageLayoutSave.Gtk.Fixed+FixedChild
		this.LabelSaveData = new global::Gtk.Label();
		this.LabelSaveData.Name = "LabelSaveData";
		this.LabelSaveData.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Save as new data</b>");
		this.LabelSaveData.UseMarkup = true;
		this.PageLayoutSave.Add(this.LabelSaveData);
		global::Gtk.Fixed.FixedChild w49 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutSave[this.LabelSaveData]));
		w49.X = 70;
		w49.Y = 390;
		// Container child PageLayoutSave.Gtk.Fixed+FixedChild
		this.NewDataFileName = new global::Gtk.Entry();
		this.NewDataFileName.WidthRequest = 300;
		this.NewDataFileName.Name = "NewDataFileName";
		this.NewDataFileName.IsEditable = true;
		this.NewDataFileName.InvisibleChar = '•';
		this.PageLayoutSave.Add(this.NewDataFileName);
		global::Gtk.Fixed.FixedChild w50 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutSave[this.NewDataFileName]));
		w50.X = 20;
		w50.Y = 340;
		// Container child PageLayoutSave.Gtk.Fixed+FixedChild
		this.LabelNewData = new global::Gtk.Label();
		this.LabelNewData.Name = "LabelNewData";
		this.LabelNewData.LabelProp = global::Mono.Unix.Catalog.GetString("<b>New Data</b>");
		this.LabelNewData.UseMarkup = true;
		this.PageLayoutSave.Add(this.LabelNewData);
		global::Gtk.Fixed.FixedChild w51 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutSave[this.LabelNewData]));
		w51.X = 20;
		w51.Y = 320;
		this.MainNotebook.Add(this.PageLayoutSave);
		global::Gtk.Notebook.NotebookChild w52 = ((global::Gtk.Notebook.NotebookChild)(this.MainNotebook[this.PageLayoutSave]));
		w52.Position = 2;
		// Notebook tab
		this.LabelPageSave = new global::Gtk.Label();
		this.LabelPageSave.Name = "LabelPageSave";
		this.LabelPageSave.LabelProp = global::Mono.Unix.Catalog.GetString("Cluster");
		this.MainNotebook.SetTabLabel(this.PageLayoutSave, this.LabelPageSave);
		this.LabelPageSave.ShowAll();
		// Container child MainNotebook.Gtk.Notebook+NotebookChild
		this.LayoutPagePlot = new global::Gtk.Fixed();
		this.LayoutPagePlot.Name = "LayoutPagePlot";
		this.LayoutPagePlot.HasWindow = false;
		// Container child LayoutPagePlot.Gtk.Fixed+FixedChild
		this.PlotImage = new global::Gtk.Image();
		this.PlotImage.WidthRequest = 640;
		this.PlotImage.HeightRequest = 400;
		this.PlotImage.Name = "PlotImage";
		this.LayoutPagePlot.Add(this.PlotImage);
		global::Gtk.Fixed.FixedChild w53 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePlot[this.PlotImage]));
		w53.X = 60;
		w53.Y = 30;
		// Container child LayoutPagePlot.Gtk.Fixed+FixedChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'PlotToolbar\'><toolitem name=\'PlotButton\' action=\'PlotButton\'/>" +
				"<toolitem name=\'SavePlotButton\' action=\'SavePlotButton\'/></toolbar></ui>");
		this.PlotToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/PlotToolbar")));
		this.PlotToolbar.Name = "PlotToolbar";
		this.PlotToolbar.ShowArrow = false;
		this.PlotToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
		this.LayoutPagePlot.Add(this.PlotToolbar);
		global::Gtk.Fixed.FixedChild w54 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePlot[this.PlotToolbar]));
		w54.X = 60;
		w54.Y = 440;
		// Container child LayoutPagePlot.Gtk.Fixed+FixedChild
		this.LabelPlotFeatures = new global::Gtk.Label();
		this.LabelPlotFeatures.Name = "LabelPlotFeatures";
		this.LabelPlotFeatures.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Features</b>");
		this.LabelPlotFeatures.UseMarkup = true;
		this.LayoutPagePlot.Add(this.LabelPlotFeatures);
		global::Gtk.Fixed.FixedChild w55 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePlot[this.LabelPlotFeatures]));
		w55.X = 270;
		w55.Y = 450;
		// Container child LayoutPagePlot.Gtk.Fixed+FixedChild
		this.LabelX = new global::Gtk.Label();
		this.LabelX.Name = "LabelX";
		this.LabelX.LabelProp = global::Mono.Unix.Catalog.GetString("X");
		this.LayoutPagePlot.Add(this.LabelX);
		global::Gtk.Fixed.FixedChild w56 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePlot[this.LabelX]));
		w56.X = 350;
		w56.Y = 450;
		// Container child LayoutPagePlot.Gtk.Fixed+FixedChild
		this.Feature1 = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.Feature1.WidthRequest = 100;
		this.Feature1.Name = "Feature1";
		this.Feature1.Adjustment.PageIncrement = 10D;
		this.Feature1.ClimbRate = 1D;
		this.Feature1.Numeric = true;
		this.LayoutPagePlot.Add(this.Feature1);
		global::Gtk.Fixed.FixedChild w57 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePlot[this.Feature1]));
		w57.X = 370;
		w57.Y = 445;
		// Container child LayoutPagePlot.Gtk.Fixed+FixedChild
		this.LabelY = new global::Gtk.Label();
		this.LabelY.Name = "LabelY";
		this.LabelY.LabelProp = global::Mono.Unix.Catalog.GetString("Y");
		this.LayoutPagePlot.Add(this.LabelY);
		global::Gtk.Fixed.FixedChild w58 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePlot[this.LabelY]));
		w58.X = 480;
		w58.Y = 450;
		// Container child LayoutPagePlot.Gtk.Fixed+FixedChild
		this.Feature2 = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.Feature2.WidthRequest = 100;
		this.Feature2.Name = "Feature2";
		this.Feature2.Adjustment.PageIncrement = 10D;
		this.Feature2.ClimbRate = 1D;
		this.Feature2.Numeric = true;
		this.Feature2.Value = 1D;
		this.LayoutPagePlot.Add(this.Feature2);
		global::Gtk.Fixed.FixedChild w59 = ((global::Gtk.Fixed.FixedChild)(this.LayoutPagePlot[this.Feature2]));
		w59.X = 500;
		w59.Y = 445;
		this.MainNotebook.Add(this.LayoutPagePlot);
		global::Gtk.Notebook.NotebookChild w60 = ((global::Gtk.Notebook.NotebookChild)(this.MainNotebook[this.LayoutPagePlot]));
		w60.Position = 3;
		// Notebook tab
		this.LabelPagePlot = new global::Gtk.Label();
		this.LabelPagePlot.Name = "LabelPagePlot";
		this.LabelPagePlot.LabelProp = global::Mono.Unix.Catalog.GetString("Plot");
		this.MainNotebook.SetTabLabel(this.LayoutPagePlot, this.LabelPagePlot);
		this.LabelPagePlot.ShowAll();
		// Container child MainNotebook.Gtk.Notebook+NotebookChild
		this.PageLayoutAbout = new global::Gtk.Fixed();
		this.PageLayoutAbout.Name = "PageLayoutAbout";
		this.PageLayoutAbout.HasWindow = false;
		// Container child PageLayoutAbout.Gtk.Fixed+FixedChild
		this.LabelAboutSoftware = new global::Gtk.Label();
		this.LabelAboutSoftware.Name = "LabelAboutSoftware";
		this.LabelAboutSoftware.LabelProp = global::Mono.Unix.Catalog.GetString("<b>GTK Clustering Software</b>");
		this.LabelAboutSoftware.UseMarkup = true;
		this.PageLayoutAbout.Add(this.LabelAboutSoftware);
		global::Gtk.Fixed.FixedChild w61 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutAbout[this.LabelAboutSoftware]));
		w61.X = 20;
		w61.Y = 20;
		// Container child PageLayoutAbout.Gtk.Fixed+FixedChild
		this.AboutWindow = new global::Gtk.ScrolledWindow();
		this.AboutWindow.WidthRequest = 310;
		this.AboutWindow.HeightRequest = 200;
		this.AboutWindow.Name = "AboutWindow";
		this.AboutWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child AboutWindow.Gtk.Container+ContainerChild
		this.AboutView = new global::Gtk.TextView();
		this.AboutView.Buffer.Text = global::Mono.Unix.Catalog.GetString(@"GTK Clustering software utilizes K-means algorithm to group data points into clusters. However, you must specify the number of clusters (K) from the 'Compute' page before running the algorithm.

Centroids are initialized at by randomly selecting K points from the input data. An option to initialize centroid values from a text file is also available. When loading data sets, the last column of each line is assumed to be the cluster number (or category). You may override this behavior by un-checking the 'Ignore last column' option. You may set the maximum number of iterations from the 'Compute page'. 

On the Cluster page, you may export and import centroids or cluster numbers to/from a text file. An option to export both sets of values into a single text file is also available.

More data sets are available at:

P. Fränti and S. Sieranoja
Applied Intelligence, 1-17, 2018
https://doi.org/10.1007/s10489-018-1238-7

http://cs.joensuu.fi/sipu/datasets/");
		this.AboutView.Name = "AboutView";
		this.AboutView.Editable = false;
		this.AboutView.CursorVisible = false;
		this.AboutView.AcceptsTab = false;
		this.AboutView.WrapMode = ((global::Gtk.WrapMode)(2));
		this.AboutWindow.Add(this.AboutView);
		this.PageLayoutAbout.Add(this.AboutWindow);
		global::Gtk.Fixed.FixedChild w63 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutAbout[this.AboutWindow]));
		w63.X = 20;
		w63.Y = 40;
		// Container child PageLayoutAbout.Gtk.Fixed+FixedChild
		this.LabelCredits = new global::Gtk.Label();
		this.LabelCredits.Name = "LabelCredits";
		this.LabelCredits.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Credits</b>");
		this.LabelCredits.UseMarkup = true;
		this.PageLayoutAbout.Add(this.LabelCredits);
		global::Gtk.Fixed.FixedChild w64 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutAbout[this.LabelCredits]));
		w64.X = 20;
		w64.Y = 260;
		// Container child PageLayoutAbout.Gtk.Fixed+FixedChild
		this.CreditsWindow = new global::Gtk.ScrolledWindow();
		this.CreditsWindow.WidthRequest = 310;
		this.CreditsWindow.HeightRequest = 100;
		this.CreditsWindow.Name = "CreditsWindow";
		this.CreditsWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child CreditsWindow.Gtk.Container+ContainerChild
		this.CreditsView = new global::Gtk.TextView();
		this.CreditsView.Buffer.Text = global::Mono.Unix.Catalog.GetString("Icons made by prettycons from www.flaticon.com is licensed by Creative Commons BY" +
				" 3.0");
		this.CreditsView.CanFocus = true;
		this.CreditsView.Name = "CreditsView";
		this.CreditsView.Editable = false;
		this.CreditsView.CursorVisible = false;
		this.CreditsView.AcceptsTab = false;
		this.CreditsView.WrapMode = ((global::Gtk.WrapMode)(2));
		this.CreditsWindow.Add(this.CreditsView);
		this.PageLayoutAbout.Add(this.CreditsWindow);
		global::Gtk.Fixed.FixedChild w66 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutAbout[this.CreditsWindow]));
		w66.X = 20;
		w66.Y = 280;
		// Container child PageLayoutAbout.Gtk.Fixed+FixedChild
		this.ClusteringImage = new global::Gtk.Image();
		this.ClusteringImage.Name = "ClusteringImage";
		this.ClusteringImage.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Clustering.atoms256.png");
		this.PageLayoutAbout.Add(this.ClusteringImage);
		global::Gtk.Fixed.FixedChild w67 = ((global::Gtk.Fixed.FixedChild)(this.PageLayoutAbout[this.ClusteringImage]));
		w67.X = 420;
		w67.Y = 80;
		this.MainNotebook.Add(this.PageLayoutAbout);
		global::Gtk.Notebook.NotebookChild w68 = ((global::Gtk.Notebook.NotebookChild)(this.MainNotebook[this.PageLayoutAbout]));
		w68.Position = 4;
		// Notebook tab
		this.LabelPageAbout = new global::Gtk.Label();
		this.LabelPageAbout.Name = "LabelPageAbout";
		this.LabelPageAbout.LabelProp = global::Mono.Unix.Catalog.GetString("About");
		this.MainNotebook.SetTabLabel(this.PageLayoutAbout, this.LabelPageAbout);
		this.LabelPageAbout.ShowAll();
		this.MainLayout.Add(this.MainNotebook);
		global::Gtk.Fixed.FixedChild w69 = ((global::Gtk.Fixed.FixedChild)(this.MainLayout[this.MainNotebook]));
		w69.X = 20;
		w69.Y = 60;
		this.Add(this.MainLayout);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.QuitButton.Activated += new global::System.EventHandler(this.OnQuitButtonClicked);
		this.AboutButton.Activated += new global::System.EventHandler(this.OnAboutButtonClicked);
		this.RunButton.Activated += new global::System.EventHandler(this.OnRunButtonClicked);
		this.ResetButton.Activated += new global::System.EventHandler(this.OnResetButtonClicked);
		this.StopButton.Activated += new global::System.EventHandler(this.OnStopButtonClicked);
		this.LoadCentroidsButton.Activated += new global::System.EventHandler(this.OnLoadCentroidsButtonClicked);
		this.SaveDataButton.Activated += new global::System.EventHandler(this.OnSaveDataButtonClicked);
		this.PlotButton.Activated += new global::System.EventHandler(this.OnPlotButtonClicked);
		this.SavePlotButton.Activated += new global::System.EventHandler(this.OnSavePlotButtonClicked);
		this.MainNotebook.SwitchPage += new global::Gtk.SwitchPageHandler(this.OnMainNotebookSwitchPage);
		this.OpenDataButton.Clicked += new global::System.EventHandler(this.OnOpenDataButtonClicked);
		this.ReloadDataButton.Clicked += new global::System.EventHandler(this.OnReloadDataButtonClicked);
		this.ClearDataButton.Clicked += new global::System.EventHandler(this.OnClearDataButtonClicked);
		this.OpenCentroidsButton.Clicked += new global::System.EventHandler(this.OnOpenCentroidsButtonClicked);
		this.SaveCentroidsButton.Clicked += new global::System.EventHandler(this.OnSaveCentroidsButtonClicked);
		this.OpenClustersButton.Clicked += new global::System.EventHandler(this.OnOpenClustersButtonClicked);
		this.SaveClustersButton.Clicked += new global::System.EventHandler(this.OnSaveClustersButtonClicked);
	}
}
